'use client';

import { KeyboardEvent, useEffect, useRef, useState } from 'react';

type CertificateVendor = { name: string; id: string; gst: string; pan: string; tier: string; score: number; commitment: string };

export default function CertificateModal({ vendor }: { vendor: CertificateVendor }) {
  const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null); const modal = useRef<HTMLDivElement>(null);
  function close() { setOpen(false); window.setTimeout(() => trigger.current?.focus(), 0); }
  function trap(event: KeyboardEvent<HTMLDivElement>) { if (event.key === 'Escape') { close(); return; } if (event.key !== 'Tab') return; const nodes = modal.current?.querySelectorAll<HTMLElement>('button'); if (!nodes?.length) return; const first = nodes[0]; const last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } }
  useEffect(() => { if (open) modal.current?.querySelector<HTMLElement>('button')?.focus(); }, [open]);
  const qr = 'M3 3h8v8H3zm2 2v4h4V5zM13 3h8v8h-8zm2 2v4h4V5zM3 13h8v8H3zm2 2v4h4v-4zM13 13h2v2h-2zm4 0h4v2h-4zm-2 4h2v4h-2zm4 0h2v2h-2zm-2 2h2v2h-2z';
  return <><button ref={trigger} className="cp-btn certificate-trigger" onClick={() => setOpen(true)}>Generate Certificate 📜</button>{open && <div className="certificate-modal" role="dialog" aria-modal="true" aria-labelledby="certificateTitle" ref={modal} onKeyDown={trap}><div className="certificate-backdrop" onClick={close} /><article className={`certificate-sheet certificate-${vendor.tier.toLowerCase()}`}><div className="certificate-actions"><button className="cp-btn" onClick={() => window.print()}>Print / Export PDF</button><button className="cp-btn" onClick={close}>Close</button></div><div className="certificate-watermark">{vendor.tier}</div><header><span className="certificate-mark">V</span><p>VENDORCHAIN / ZERO-TRUST NETWORK</p><h2 id="certificateTitle">Certificate of Verification</h2><span>Cryptographically verifiable supply-chain identity record</span></header><section className="certificate-meta"><div><small>LEGAL NAME</small><strong>{vendor.name}</strong></div><div><small>CUID</small><code>{vendor.id}</code></div><div><small>MASKED GSTIN</small><code>{vendor.gst}</code></div><div><small>MASKED PAN</small><code>{vendor.pan}</code></div><div><small>ISSUED</small><code>{new Date().toISOString().replace('T', ' ').slice(0, 19)} UTC</code></div><div><small>TRUST TIER</small><strong>{vendor.tier} / {vendor.score}</strong></div></section><section className="certificate-seals"><div><b>01 / Mod-36 GSTIN Checksum Seal</b><strong>ISO/IEC 7064 VERIFIED</strong><span>Indian tax identity integrity confirmed</span></div><div><b>02 / Cosign Ed25519 Signature Stamp</b><strong>KEY ID: cosign.pub</strong><span>Artifact signer cryptographically valid</span></div><div><b>03 / Polygon L2 State Commitment</b><code>{vendor.commitment.slice(0, 18)}…</code><svg viewBox="0 0 24 24" aria-label="State commitment QR code"><path d={qr} /></svg></div></section><p className="certificate-live" aria-live="polite">Certificate rendered with active {vendor.tier} policy watermark.</p></article></div>}</>;
}
