'use client';

import { useState } from 'react';

type Vendor = { id: string; name: string; gst: string; pan: string; status: string; verifiedDate: string; score: number; tier: string; supply: number };
type Document = { id: string; type: string; sha: string; status: string };
type Transaction = { id: string; invoice: string; hash: string; block: number | null; status: string; reason: string | null };
const tabs = ['docs', 'supply', 'ledger'] as const;

export default function RaiseDisputeModal({ vendor, documents, transactions }: { vendor: Vendor; documents: Document[]; transactions: Transaction[] }) {
  const [tab, setTab] = useState<typeof tabs[number]>('docs'); const [open, setOpen] = useState<string | null>(null); const [category, setCategory] = useState('SLA Breach'); const [notes, setNotes] = useState('');
  const [score, setScore] = useState(vendor.score); const [tier, setTier] = useState(vendor.tier); const [ledger, setLedger] = useState(transactions); const [alert, setAlert] = useState(''); const [busy, setBusy] = useState(false);
  const critical = score < 40; const remediation = score < 85;
  async function submit() { if (!open) return; setBusy(true); const result = await fetch(`/api/vendors/${vendor.id}/transactions/${open}/dispute`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-admin-key': '' }, body: JSON.stringify({ disputeReason: `${category}: ${notes || 'Raised via deep vendor vault'}` }) }); const data = await result.json(); setBusy(false); if (!result.ok) { setAlert(data.error ?? 'Dispute could not be raised.'); return; } const after = Math.min(39, data.trustFeedback.afterScore); setScore(after); setTier('TIER_4_SUSPENDED'); setLedger((items) => items.map((item) => item.id === open ? { ...item, status: 'DISPUTED', reason: category } : item)); setOpen(null); setAlert(`-25 Point Anomaly Penalty Applied — Score Dropped to ${after}`); }
  return <><section className="vault-header"><div><a className="vault-link" href="/dashboard">← Dashboard</a><h1>{vendor.name}</h1><div className="vault-meta-grid"><span>CUID <code>{vendor.id}</code></span><span>GSTIN <code>{vendor.gst}</code></span><span>PAN <code>{vendor.pan}</code></span><span>Verified <code>{vendor.verifiedDate}</code></span></div><span className={`status-tag status-${vendor.status.toLowerCase()}`}>{vendor.status}</span></div><div className="vault-gauge"><svg viewBox="0 0 160 160" role="img" aria-label={`Trust score ${score}`}><circle className="vault-gauge-track" cx="80" cy="80" r="66" /><circle className={`vault-gauge-arc ${critical ? 'gauge-critical' : 'gauge-safe'}`} cx="80" cy="80" r="66" pathLength="100" strokeDasharray="100" strokeDashoffset={100 - score} /></svg><strong>{score}</strong><span>{tier}</span></div><div className="vault-sparkline" aria-label="30 day score history">▁▂▃▄▅▅▆▆▇▆▇▇▆▇▇▇▆▇▆▇▇▆▇▇▆▅▄▅▄▃</div></section>
    {alert && <div className="penalty-alert" role="alert">{alert}</div>}{remediation && <aside className="remediation-box"><strong>Automated remediation</strong><span>Resolve flagged evidence, re-run Cosign verification, and clear the dispute to restore a score above 85.</span></aside>}
    <nav className="vault-tab-bar" aria-label="Vault navigation">{tabs.map((item) => <button className={`vault-tab-btn ${tab === item ? 'active' : ''}`} onClick={() => setTab(item)} key={item}>{item === 'docs' ? 'Document Vault' : item === 'supply' ? 'Supply Chain Security' : 'Transaction Ledger'}</button>)}</nav>
    <section className="vault-tab-content">{tab === 'docs' && <div className="doc-vault-grid">{documents.map((doc) => <article className="doc-vault-card" key={doc.id}><strong>{doc.type.replace('_', ' ')}</strong><span>AES-256-GCM Wrapped</span><code>SHA-256 {doc.sha.slice(0, 20)}…</code><small>{doc.status}</small><div className="doc-vault-actions"><button className="cp-btn">Audited Decrypt &amp; View</button></div></article>)}{!documents.length && <p className="cp-sub">No encrypted documents are present.</p>}</div>}{tab === 'supply' && <div className="supply-vault"><article className="cosign-card"><strong>Cosign Ed25519 Signature</strong><span className={vendor.supply >= 85 ? 'signature-good' : 'signature-bad'}>{vendor.supply >= 85 ? 'VERIFIED' : 'REQUIRES REVIEW'}</span><code>issuer: github-actions / key: 7A:91:ED:25</code></article><div className="sbom-lite"><h4>CycloneDX v1.5 SBOM</h4>{[['next@14.2.5', 'LOW', '2.3'], ['bullmq@5.8.7', 'MEDIUM', '5.1'], ['ioredis@5.4.1', 'LOW', '1.8'], ['pdf-parse@1.1.1', 'HIGH', '7.4']].map((item) => <div key={item[0]}><code>{item[0]}</code><span className={`cvss-${item[1]!.toLowerCase()}`}>CVSS {item[2]!} · {item[1]!}</span></div>)}</div></div>}{tab === 'ledger' && <div className="ledger-list">{ledger.map((tx) => <article className={`ledger-entry ${tx.status === 'DISPUTED' ? 'disputed' : ''}`} key={tx.id}><div><strong>{tx.invoice}</strong><code>{tx.hash}</code><span>Polygon L2 Block #{tx.block ?? 'pending'} · {tx.status}</span>{tx.reason && <small>{tx.reason}</small>}</div><div className="ledger-actions"><button className="cp-btn">Verify Hash</button>{tx.status !== 'DISPUTED' && <button className="cp-btn danger" onClick={() => setOpen(tx.id)}>Raise Dispute</button>}</div></article>)}{!ledger.length && <p className="cp-sub">No transaction ledger records.</p>}</div>}</section>
    {open && <div className="dispute-modal" role="dialog" aria-modal="true" aria-label="Raise a transaction dispute"><div className="dispute-modal-backdrop" onClick={() => setOpen(null)} /><form className="dispute-modal-content" onSubmit={(event) => { event.preventDefault(); void submit(); }}><h3>Raise dispute</h3><label>Dispute Category<select className="dispute-select" value={category} onChange={(event) => setCategory(event.target.value)}><option>SLA Breach</option><option>Defective Software Build</option><option>Billing Mismatch</option><option>Security Incident</option></select></label><label>Optional notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div><button className="cp-btn" type="button" onClick={() => setOpen(null)}>Cancel</button><button className="cp-btn danger" disabled={busy}>{busy ? 'Applying penalty…' : 'Confirm dispute'}</button></div></form></div>}</>;
}
