'use client';

import Link from 'next/link';
import { useMemo, useState } from 'react';
import type { DashboardSummary } from '@/lib/dashboard/summary';

type Tier = 'ALL' | 'TIER_1_CRITICAL' | 'TIER_2_STANDARD' | 'TIER_3_RESTRICTED' | 'TIER_4_SUSPENDED';
type Vendor = { id: string; legalName: string; gstin: string; identity: string; supply: string; score: number; tier: Exclude<Tier, 'ALL'> };
const tiers: { id: Exclude<Tier, 'ALL'>; label: string; className: string }[] = [{ id: 'TIER_1_CRITICAL', label: 'Tier 1 Critical', className: 'tier-one' }, { id: 'TIER_2_STANDARD', label: 'Tier 2 Standard', className: 'tier-two' }, { id: 'TIER_3_RESTRICTED', label: 'Tier 3 Restricted', className: 'tier-three' }, { id: 'TIER_4_SUSPENDED', label: 'Tier 4 Suspended', className: 'tier-four' }];
const maskGstin = (value: string) => `${value.slice(0, 2)}${'•'.repeat(9)}${value.slice(-4)}`;

export default function TierDistributionBar({ summary, vendors }: { summary: DashboardSummary; vendors: Vendor[] }) {
  const [tier, setTier] = useState<Tier>('ALL'); const [search, setSearch] = useState('');
  const filtered = useMemo(() => vendors.filter((vendor) => (tier === 'ALL' || vendor.tier === tier) && `${vendor.legalName} ${vendor.gstin} ${vendor.id}`.toLowerCase().includes(search.toLowerCase())), [vendors, tier, search]);
  const anomalies = vendors.filter((vendor) => vendor.tier === 'TIER_4_SUSPENDED' || vendor.identity === 'FLAGGED' || vendor.identity === 'DISPUTED');
  const compliance = summary.totalVendors ? Math.round((summary.tierDistribution.TIER_1_CRITICAL + summary.tierDistribution.TIER_2_STANDARD) / summary.totalVendors * 100) : 0;
  return <><section className="metrics-grid" aria-label="Network telemetry"><article className="metric-card"><span>Monitored Vendors</span><strong className="metric-value">{summary.totalVendors}</strong><small className="metric-delta pulse">● active monitoring</small></article><article className="metric-card"><span>Compliance Rate</span><strong className="metric-value metric-blue">{compliance}%</strong><small className="metric-delta">Tier 1 + Tier 2 posture</small></article><article className="metric-card"><span>Active Anomaly Alerts</span><strong className="metric-value metric-crimson">{anomalies.length + summary.activeDisputes}</strong><small className="metric-delta">suspended / disputed</small></article><article className="metric-card"><span>Polygon L2 Commitments</span><strong className="metric-value metric-cyan">{summary.l2StateCommitments}</strong><small className="metric-delta">anchored state hashes</small></article></section>
    <section className="tier-bar-wrapper" aria-label="Trust tier distribution"><div className="tier-bar">{tiers.map((item) => { const count = summary.tierDistribution[item.id]; return <button className={`tier-bar-segment ${item.className} ${tier === item.id ? 'active' : ''}`} onClick={() => setTier(item.id)} aria-label={`Filter ${item.label}: ${count} vendors`} key={item.id} />; })}</div><div className="tier-legend">{tiers.map((item) => { const count = summary.tierDistribution[item.id]; const percent = summary.totalVendors ? Math.round(count / summary.totalVendors * 100) : 0; return <button className={`tier-legend-item ${item.className}`} onClick={() => setTier(item.id)} key={item.id}>{item.label}<b>{count} · {percent}%</b></button>; })}</div></section>
    <section className="anomaly-panel"><div className="anomaly-title">Cliff-drop anomaly incidents <span>{anomalies.length}</span></div>{anomalies.length ? anomalies.map((vendor) => <article className="anomaly-item" key={vendor.id}><div><strong>{vendor.legalName}</strong><code>{vendor.id}</code></div><span className="anomaly-reason-pill">{vendor.identity === 'DISPUTED' ? 'Active Dispute' : vendor.identity === 'FLAGGED' ? 'GSTIN Checksum Mismatch' : 'CVSS 9.8 / Zero-trust cliff drop'}</span><Link href={`/vendors/${vendor.id}`}>Inspect Vault ➔</Link></article>) : <p className="anomaly-empty">No suspended, flagged, or disputed vendors are currently detected.</p>}</section>
    <section className="vendor-index"><div className="vendor-tools"><input className="table-search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search legal name, GSTIN, or CUID" aria-label="Search vendors" /><div className="filter-chips"><button className={`filter-chip ${tier === 'ALL' ? 'filter-chip-active' : ''}`} onClick={() => setTier('ALL')}>All Tiers</button>{tiers.map((item) => <button className={`filter-chip ${tier === item.id ? 'filter-chip-active' : ''}`} onClick={() => setTier(item.id)} key={item.id}>{item.label.replace(' Critical', '').replace(' Standard', '').replace(' Restricted', '').replace(' Suspended', ' Only')}</button>)}</div></div><div className="vendor-table-wrap"><table className="vendor-table"><thead><tr><th>Legal Name / CUID</th><th>Masked GSTIN</th><th>Identity</th><th>Supply Chain</th><th>Trust Score</th><th /></tr></thead><tbody>{filtered.map((vendor) => <tr key={vendor.id}><td><strong>{vendor.legalName}</strong><code>{vendor.id}</code></td><td className="cp-mono">{maskGstin(vendor.gstin)}</td><td><span className={`status-tag status-${vendor.identity.toLowerCase()}`}>{vendor.identity}</span></td><td><span className={`status-tag supply-${vendor.supply.toLowerCase()}`}>{vendor.supply}</span></td><td><span className={`score-badge ${tiers.find((item) => item.id === vendor.tier)?.className}`}>{vendor.score}</span></td><td><Link href={`/vendors/${vendor.id}`}>View Vault ➔</Link></td></tr>)}{!filtered.length && <tr><td className="table-empty" colSpan={6}>No vendor records match this filter matrix.</td></tr>}</tbody></table></div></section></>;
}
